### ISSUE TITLE
Support PTT, SYM and FN keys

### ISSUE THREAD

**Issue by rfmejia** [rumplestilzken/gargoyle_lineageos20#11]
Enable the use and customization of PTT, SYM and FN keys. AFAIK these keys have no function on the Titan Pocket (unsure about other Titan devices). I can't tell if the key event is not emitted correctly (or even at all) in the current release.

Some examples of where they were useful in the stock ROM:

- Short/long/double press PTT to launch apps, turn on do not disurb or the flashlight, etc.
- SYM key with Blackberry keyboard opens custom symbols UI, or SYM+key for quick symbol insertion
- Remap FN to Ctrl for traditional shortcuts like Ctrl+a, Ctrl+c, etc.

**Comment by michalko58** [comment]
I think, that here could help that app from stock rom dealing with these keys. It should be one of the Intelligent Assistance apps by Unihertz.

**Comment by rumplestilzken** [comment]
I will be looking into the stock apps a little more today to see if i can get something working.

**Comment by mxmkchmn** [comment]
any updates on that?

**Comment by rumplestilzken** [comment]
Nothing at the moment. The next release will include keymapper.

**Comment by rumplestilzken** [comment]
Key Mapper included by default as a system app.
